name: carbonplan
channels:
  - conda-forge
dependencies:
  - pangeo-notebook=2021.03.06
  - adlfs
  - bottleneck
  - cartopy
  - code-server
  - fastparquet
  - fuzzywuzzy
  - gcsfs
  - gdal
  - geopandas
  - git-crypt
  - gspread
  - h5py
  - h5netcdf
  - hypothesis
  - intake
  - intake-excel
  - intake-geopandas
  - intake-parquet
  - intake-stac
  - intake-xarray
  - ipykernel
  - ipython
  - ipytree
  - ipywidgets
  - jedi
  - jupyterlab
  - jupyter-server-proxy
  - jupyter-vscode-proxy
  - libgdal
  - matplotlib
  - nb_conda_kernels
  - netcdf4
  - nodejs
  - numba
  - numcodecs
  - numpy
  - oauth2client
  - openpyxl
  - pandas
  - pre_commit
  - pygraphviz
  - pygeos
  - pyproj
  - pystac
  - pytest
  - python-graphviz
  - python-wget
  - rasterio
  - regionmask
  - rio-cogeo
  - rioxarray
  - scikit-learn
  - scipy
  - seaborn
  - tenacity
  - tqdm
  - xarray
  - yarn
  - zarr
  - pip
  - pip:
      - carbonplan
      - carbonplan-data
      - carbonplan-forests
      - carbonplan-styles
      - git+https://github.com/jhamman/zarr.git@be323ac4fbe58d9af66ac96c51604f514ce0149d  # for current version of azure api
